title: Wenbo Xu's Homepage
page-top-title: Wenbo Xu
top-section-bg-text: Science in Cross-disciplinary Technologies
home-subtitle: Wenbo Xu&ensp;|&ensp;徐文博
copyright-text: '&copy; Wenbo Xu 2024-2025. All Rights Reserved.'
